.TH "OPI.cpp" 3 "Sat Feb 19 2022" "Version 1" "OPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Person\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBConsoleOut\fP (string name, string age)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ConsoleOut (string name, string age)"

.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.br
\fIname\fP - people name 
.br
\fIage\fP - people age 
.RE
.PP

.SS "int main ()"
\fI\fBPerson\fP\fP create class object
.SH "Author"
.PP 
Generated automatically by Doxygen for OPI from the source code\&.
