.TH "Person.h" 3 "Sat Feb 19 2022" "Version 1" "OPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPerson\fP"
.br
.RI "Parent class that does not carry any semantic load\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPI from the source code\&.
