.TH "Person" 3 "Sat Feb 19 2022" "Version 1" "OPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person \- Parent class that does not carry any semantic load\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Person\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "person name "
.ti -1c
.RI "std::string \fBage\fP"
.br
.RI "person age "
.in -1c
.SH "Detailed Description"
.PP 
Parent class that does not carry any semantic load\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string Person::age"

.PP
person age 
.SS "std::string Person::name"

.PP
person name 

.SH "Author"
.PP 
Generated automatically by Doxygen for OPI from the source code\&.
